### PR TITLE
Initial commit of CLI, new app generator

### PR DESCRIPTION
**Pull request by andrewhavens**
At our last MotionPDX meetup, we had some fun playing around with tvOS!

This PR adds the following:
- The beginnings of a CLI tool.
- A `new` command for generating new apps.
- A typical *Potion app delegate.
- A `BP::TVMLScreen` which abstracts the gritty details of setting up a `TVApplicationController`. It also makes it a little more explicit that you are intending to use TVML.

@jamonholmgren @danhealy What do you think of this?

### CODE REVIEW

**Comment by danhealy** [comment]
Seems like a great start!

**Comment by jamonholmgren** [comment]
Looks great! Should check with @kevinvangelder ... he's spent more time in tvOS land.

**Comment by wndxlori** [comment]
Why is this not merged?

**Comment by jamonholmgren** [comment]
Happy to merge if you want! Haven't done much with BlackPotion since we gave it a spin.

**Comment by andrewhavens** [comment]
@jamonholmgren @wndxlori I'm wondering if it makes more sense to continue development of BlackPotion outside of the Infinite Red GitHub organization. Considering this repo started empty and all of the code so far has been written by me. The only Infinite Red contribution so far is the name. What do you guys think?

**Comment by jamonholmgren** [comment]
@andrewhavens I'm happy to transfer it to you. Will do when I get to a computer

**Comment by jamonholmgren** [comment]
@andrewhavens I made you an admin -- go ahead and transfer it to yourself. (This is how Github wants us to do it I guess)

**Pull request merged**
